// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilzbtmlakphgvhlpfggs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsemJ0bWxha3BoZ3ZobHBmZ2dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjg5MzEsImV4cCI6MjA2MTcwNDkzMX0.7B3-U6D-GgpEVra8BAFeGCaqt22SegR4w507_Xe9SfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);